# Generated by Django 2.2.7 on 2019-11-24 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=75, unique_for_date='registered_date')),
                ('category', models.CharField(max_length=75)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('details', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
