# Generated by Django 2.2.7 on 2019-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('mog', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ('surname', 'name', 'mog'),
            },
        ),
    ]
